name: Scan
on:
  workflow_dispatch

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Chain Bench Scan
    steps:
      - name: Chain Bench
        id: chain-bench
        uses: aquasecurity/chain-bench-action@v1.1.1
        with:
          repository-url: ${{ github.server_url }}/${{ github.repository }} # Compiles to https://github.com/aquasecurity/chain-bench-action
          github-token: ${{ secrets.CB_TOKEN }}
          scm-platform: github #Optional parameter for dedicated SCM servers

      - name: Save to file 
        run: echo ${{ steps.chain-bench.outputs.chain-bench-result }} > /tmp/report.json

      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report.json
          path: /tmp/report.json
  
